# -*- coding: utf-8 -*-
"""UFC _ligthweight_Division_Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2G-4du7EPIyopnbtv7aLP1LWOzU6cbq
"""

import requests

api_key = "123"

url = f"https://www.thesportsdb.com/api/v1/json/123/eventsseason.php"

params = {
    "id": "4443",
    "s": "2026"
}

response = requests.get(url, params=params)

data = response.json()

print(data)

import json

print(json.dumps(data, indent=4))

df.columns

events = data["events"]

df_events = pd.DataFrame(events)
print(df_events.columns)

df_clean = df_events[[
    "idEvent",
    "strEvent",
    "strTimestamp",
    "strLeague",
    "strSeason",
    "strHomeTeam",
    "strAwayTeam",
    "intHomeScore",
    "intAwayScore",
    "strVenue"
]]

df_clean.head(10)

import pandas as pd

ufc = pd.read_csv("ufc_event_fight_stats.csv")


ufc.head()

ufc.columns

df = pd.DataFrame(ufc)

important_cols = [
    "f1_name", "f2_name",
    "weight_class",

    "f1_age_during", "f2_age_during",
    "f1_height_cm", "f2_height_cm",

    "f1_sig_strikes", "f2_sig_strikes",
    "f1_takedowns", "f2_takedowns",
    "f1_ctrl_time", "f2_ctrl_time",
    "f1_submissions", "f2_submissions",
    "f1_knockdowns", "f2_knockdowns",

    "result"
]

df_clean = df[important_cols]

df_clean.head()

df_clean.shape

df_clean.info()

df_clean.describe()

df.isnull().sum()

df_clean.duplicated().sum()

df_clean.head()

df['weight_class'].unique()

df['weight_class'].value_counts()

filtered_fights = df_clean[
    df_clean["weight_class"].str.contains(
        "Lightweight|Middleweight|Featherweight",
        case=False,
        na=False
    )
]

print(filtered_fights)

filtered_fights.head()

df1 = pd.DataFrame(filtered_fights)

df1.groupby("f1_name")["f1_takedowns"].sum()

df1.shape

df1["total_submissions"] = df1["f1_submissions"] + df1["f2_submissions"]

lightweight_df = df_clean[
    df_clean["weight_class"].str.contains(
        "Lightweight",
        case=False,
        na=False
    )
]

df2 = pd.DataFrame(lightweight_df)

df2.head()



df2.shape

fighters = pd.concat([
    df2['f1_name'],
    df2['f2_name']
])

total_fighters = fighters.nunique()
print(total_fighters)

all_fighters = pd.concat([df2["f1_name"], df2["f2_name"]])


print(all_fighters)

fight_counts = all_fighters.value_counts()

print(fight_counts)

fight_counts[fight_counts >= 3]

df2.columns

df2["f1_score"] = (
    df2["f1_sig_strikes"] +
    df2["f1_takedowns"] * 5 +
    df2["f1_knockdowns"] * 10 +
    df2["f1_ctrl_time"] +
    df2["f1_submissions"] * 5
)

df2["f2_score"] = (
    df2["f2_sig_strikes"] +
    df2["f2_takedowns"] * 5 +
    df2["f2_knockdowns"] * 10 +
    df2["f2_ctrl_time"] +
    df2["f2_submissions"] * 5
)

df2["winner"] = df2.apply(
    lambda x: x["f1_name"] if x["f1_score"] > x["f2_score"] else x["f2_name"],
    axis=1
)

df2["winner"].value_counts()

df2["winner"].head(20)

wins = df2["winner"].value_counts()

print(wins)

stats = pd.DataFrame({
    "fights": fight_counts,
    "wins": wins
}).fillna(0)

stats["win_rate"] = stats["wins"] / stats["fights"]

print(stats)

df2["winner"].sample(30)

lw_df = df2[df2["weight_class"].str.contains("Lightweight", case=False, na=False)]

lw_wins = lw_df["winner"].value_counts()

fighters = [
    "Khabib Nurmagomedov",
    "Islam Makhachev",
    "Conor McGregor",
    "Charles Oliveira",
    "Ilia Topuria"
]

for f in fighters:
    print(f, lw_wins.get(f, 0))

